name: job_sequencer
description: Manages sequential job execution, ensuring jobs run in order, crucial for ordered task processing.
version: 1.2.0
repository: https://github.com/TimeLord2010/job_sequencer

environment:
  sdk: ^3.7.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
